# Generated by Django 6.1 on 2026-08-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pa', 'Progressão Aritmética (P.A.)'), ('pg', 'Progressão Geométrica (P.G.)')], default='pa', max_length=2)),
                ('a1', models.FloatField(default=1.0, verbose_name='Primeiro Termo (a1)')),
                ('razao', models.FloatField(default=2.0, verbose_name='Razão (r ou q)')),
                ('n', models.IntegerField(default=10, verbose_name='Número de Termos (n)')),
                ('soma_calculada', models.FloatField(blank=True, null=True, verbose_name='Soma dos Termos')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Simulação',
                'verbose_name_plural': 'Simulações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
