# Generated by Django 6.1 on 2026-08-17 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(default='🏆', max_length=10)),
                ('xp_necessario', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('enunciado', models.TextField()),
                ('categoria', models.CharField(choices=[('exp_log', 'Exponenciais e Logaritmos'), ('matrizes', 'Matrizes e Determinantes'), ('trigonometria', 'Trigonometria')], max_length=20)),
                ('alvo_base', models.FloatField(help_text='Valor correto da base (a)')),
                ('alvo_k', models.FloatField(help_text='Valor correto do multiplicador (k)')),
                ('tolerancia', models.FloatField(default=0.1, help_text='Margem de erro aceitável')),
                ('xp_recompensa', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_total', models.IntegerField(default=0)),
                ('badges', models.ManyToManyField(blank=True, to='desafios.badge')),
                ('desafios_concluidos', models.ManyToManyField(blank=True, to='desafios.desafio')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_math', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
